### PR TITLE
adds jshintc and dir-locals to conform to repo style

### PR DESCRIPTION
**Pull request by DEADB17**

### CODE REVIEW

**Comment by DEADB17** [comment]
Hello. I added a few features that I need to your library.
Each of the branches on the pull-requests is based on the previous one. i.e.: the last pull request includes all of them. They are pretty focused, so hopefully it'll be easy to review.
I'm hoping we can collaborate, but if you are not interested in this direction or don't have the time please let me know so that I push a new package to NPM. Or if you are not interested in maintaining it anymore maybe you can transfer it.
Anyhow, thanks for your work.
Cheers

**Comment by DEADB17** [comment]
I'm reviewing alternatives that are somewhat closer to the original.
I'll reopen once I'm satisfied.

**Comment by shime** [comment]
Cool, thanks for your contribution! No need to open so many pull requests, just open a big one with all the changes you want to merge in and I'll be happy to review and pull it in. We can discuss everything in the inline comments. 

Thanks!

**Comment by DEADB17** [comment]
Sorry for the confusion, but i closed them all since I'm working on a
better version more in line with the original minimalism. I'll send new
pull requests soon.

**Pull request closed without merging**
